version: 2

aliases:
  # build environment
  - &docker-linux
    docker:
      - image: centos:7
    working_directory: /root/src

  # system dependencies
  - &install-deps
    run:
      name: Install system dependencies
      command: |
        yum update -y --exclude=filesystem
        yum install -y zlib-devel
  - &install-stack
    run:
      name: Install stack
      command: curl -sSL https://get.haskellstack.org/ | sh

  # cache
  - &build-cache-key
    run:
      name: Build cache key
      command: |
        FILES=(
          stack.yaml
          scripts/setup.sh
          persistent-migration.cabal
        )
        cat "${FILES[@]}" > cache-key.txt
  - &cache-key
    v1-{{ checksum "cache-key.txt" }}
  - &build-deps
    run:
      name: Build external dependencies
      command: scripts/setup.sh

  # build steps
  - &run-build
    run:
      name: Build package
      command: stack build --test --no-run-tests

  # test steps
  - &run-test
    run:
      name: Run tests
      command: stack test
  - &run-hlint
    run:
      name: Run HLint
      command: scripts/hlint.sh
  - &run-stylish-haskell
    run:
      name: Run stylish-haskell
      command: scripts/stylish-haskell.sh

jobs:
  prebuild:
    <<: *docker-linux
    steps:
      - checkout
      - *build-cache-key
      - persist_to_workspace:
          root: .
          paths:
            - cache-key.txt

  build:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-deps
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *build-deps
      - save_cache:
          key: *cache-key
          paths:
            - ~/.stack
      - *run-build
      - persist_to_workspace:
          root: .
          paths:
              - .stack-work

  test:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-test

  hlint:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-hlint

  stylish-haskell:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-stylish-haskell

workflows:
  version: 2

  build_and_test:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
      - test:
          requires:
            - build
      - hlint:
          requires:
            - build
      - stylish-haskell:
          requires:
            - build
