version: 2

aliases:
  # build environment
  - &docker-linux
    docker:
      - image: centos:7
    working_directory: /root/src

  # system dependencies
  - &install-system-deps
    run:
      name: Install system dependencies
      command: scripts/install-system-deps.sh
  - &install-stack
    run:
      name: Install stack
      command: |
        curl -sSL https://get.haskellstack.org/ | sh
        stack --version

  # cache
  - &build-cache-key
    run:
      name: Build cache key
      command: |
        FILES=(
          stack.yaml
          scripts/install-stack-deps.sh
          persistent-migration.cabal
        )
        cat "${FILES[@]}" > cache-key.txt
  - &cache-key
    v2-{{ checksum "cache-key.txt" }}
  - &install-stack-deps
    run:
      name: Build external dependencies
      command: scripts/install-stack-deps.sh

  # build steps
  - &run-build
    run:
      name: Build package
      command: stack build --flag persistent-migration:dev --test --no-run-tests

  # test steps
  - &run-unit-tests
    run:
      name: Run unit tests
      command: |
        DIR=$(stack path --dist-dir)/build/persistent-migration-test
        ${DIR}/persistent-migration-test
  - &run-integration-tests
    run:
      name: Run integration tests
      command: |
        # integration tests need to run as non-root
        useradd test
        DIR=$(stack path --dist-dir)/build/persistent-migration-integration
        su test -c "${DIR}/persistent-migration-integration"
  - &run-hlint
    run:
      name: Run HLint
      command: scripts/hlint.sh
  - &run-stylish-haskell
    run:
      name: Run stylish-haskell
      command: scripts/stylish-haskell.sh

jobs:
  prebuild:
    <<: *docker-linux
    steps:
      - checkout
      - *build-cache-key
      - persist_to_workspace:
          root: .
          paths:
            - cache-key.txt

  build:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-system-deps
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *install-stack-deps
      - save_cache:
          key: *cache-key
          paths:
            - ~/.stack
            - .stack-work
      - *run-build
      - persist_to_workspace:
          root: .
          paths:
              - .stack-work

  unit-tests:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-unit-tests

  integration-tests:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-system-deps
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-integration-tests

  hlint:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-hlint

  stylish-haskell:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-stylish-haskell

workflows:
  version: 2

  build_and_test:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
      - unit-tests:
          requires:
            - build
      - integration-tests:
          requires:
            - build
      - hlint:
          requires:
            - build
      - stylish-haskell:
          requires:
            - build

  nightly:
    triggers:
      - schedule:
          cron: "0 8 * * *"  # midnight PST
          filters:
            branches:
              only:
                - master
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
      - unit-tests:
          requires:
            - build
      - integration-tests:
          requires:
            - build
      - hlint:
          requires:
            - build
      - stylish-haskell:
          requires:
            - build
